// Mocks generated by Mockito from annotations
// in riverpod_with_clean_arch/test/features/settings/settings_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:riverpod_with_clean_arch/src/common/patterns/result_pattern.dart'
    as _i5;
import 'package:riverpod_with_clean_arch/src/common/services/storage_service.dart'
    as _i2;
import 'package:riverpod_with_clean_arch/src/features/settings/data/data.dart'
    as _i4;
import 'package:riverpod_with_clean_arch/src/features/settings/domain/domain.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initStorage() => (super.noSuchMethod(
    Invocation.method(#initStorage, []),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<bool?> getBoolValue({required String? key}) => (super.noSuchMethod(
    Invocation.method(#getBoolValue, [], {#key: key}),
    returnValue: _i3.Future<bool?>.value(),
  ) as _i3.Future<bool?>);

  @override
  _i3.Future<void> setBoolValue({required String? key, required bool? value}) =>
      (super.noSuchMethod(
        Invocation.method(#setBoolValue, [], {#key: key, #value: value}),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeValue({required String? key}) => (super.noSuchMethod(
    Invocation.method(#removeValue, [], {#key: key}),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearStorage() => (super.noSuchMethod(
    Invocation.method(#clearStorage, []),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);
}

/// A class which mocks [SettingDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingDataSource extends _i1.Mock implements _i4.SettingDataSource {
  MockSettingDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.ResultPattern<_i4.SettingModel, _i4.SettingException>>
  readTheme() => (super.noSuchMethod(
    Invocation.method(#readTheme, []),
    returnValue:
        _i3.Future<
          _i5.ResultPattern<_i4.SettingModel, _i4.SettingException>
        >.value(
          _i6.dummyValue<
            _i5.ResultPattern<_i4.SettingModel, _i4.SettingException>
          >(this, Invocation.method(#readTheme, [])),
        ),
  ) as _i3.Future<_i5.ResultPattern<_i4.SettingModel, _i4.SettingException>>);

  @override
  _i3.Future<_i5.ResultPattern<void, _i4.SettingException>> updateTheme({
    required bool? isDarkTheme,
  }) => (super.noSuchMethod(
    Invocation.method(#updateTheme, [], {#isDarkTheme: isDarkTheme}),
    returnValue:
        _i3.Future<_i5.ResultPattern<void, _i4.SettingException>>.value(
          _i6.dummyValue<_i5.ResultPattern<void, _i4.SettingException>>(
            this,
            Invocation.method(#updateTheme, [], {#isDarkTheme: isDarkTheme}),
          ),
        ),
  ) as _i3.Future<_i5.ResultPattern<void, _i4.SettingException>>);
}

/// A class which mocks [SettingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingRepository extends _i1.Mock implements _i7.SettingRepository {
  MockSettingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.ResultPattern<_i7.SettingEntity, _i4.SettingException>>
  readTheme() => (super.noSuchMethod(
    Invocation.method(#readTheme, []),
    returnValue:
        _i3.Future<
          _i5.ResultPattern<_i7.SettingEntity, _i4.SettingException>
        >.value(
          _i6.dummyValue<
            _i5.ResultPattern<_i7.SettingEntity, _i4.SettingException>
          >(this, Invocation.method(#readTheme, [])),
        ),
  ) as _i3.Future<_i5.ResultPattern<_i7.SettingEntity, _i4.SettingException>>);

  @override
  _i3.Future<_i5.ResultPattern<void, _i4.SettingException>> updateTheme({
    required bool? isDarkTheme,
  }) => (super.noSuchMethod(
    Invocation.method(#updateTheme, [], {#isDarkTheme: isDarkTheme}),
    returnValue:
        _i3.Future<_i5.ResultPattern<void, _i4.SettingException>>.value(
          _i6.dummyValue<_i5.ResultPattern<void, _i4.SettingException>>(
            this,
            Invocation.method(#updateTheme, [], {#isDarkTheme: isDarkTheme}),
          ),
        ),
  ) as _i3.Future<_i5.ResultPattern<void, _i4.SettingException>>);
}

/// A class which mocks [ReadThemeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadThemeUseCase extends _i1.Mock implements _i7.ReadThemeUseCase {
  MockReadThemeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.ResultPattern<_i7.SettingEntity, _i4.SettingException>>
  call() => (super.noSuchMethod(
    Invocation.method(#call, []),
    returnValue:
        _i3.Future<
          _i5.ResultPattern<_i7.SettingEntity, _i4.SettingException>
        >.value(
          _i6.dummyValue<
            _i5.ResultPattern<_i7.SettingEntity, _i4.SettingException>
          >(this, Invocation.method(#call, [])),
        ),
  ) as _i3.Future<_i5.ResultPattern<_i7.SettingEntity, _i4.SettingException>>);
}

/// A class which mocks [UpdateThemeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateThemeUseCase extends _i1.Mock
    implements _i7.UpdateThemeUseCase {
  MockUpdateThemeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.ResultPattern<void, _i4.SettingException>> call({
    required bool? isDarkTheme,
  }) => (super.noSuchMethod(
    Invocation.method(#call, [], {#isDarkTheme: isDarkTheme}),
    returnValue:
        _i3.Future<_i5.ResultPattern<void, _i4.SettingException>>.value(
          _i6.dummyValue<_i5.ResultPattern<void, _i4.SettingException>>(
            this,
            Invocation.method(#call, [], {#isDarkTheme: isDarkTheme}),
          ),
        ),
  ) as _i3.Future<_i5.ResultPattern<void, _i4.SettingException>>);
}
